services:
  ocis:
    image: ${OCIS_DOCKER_IMAGE:-owncloud/ocis}:${OCIS_VERSION_TAG:-latest}
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - 9200:9200
    environment:
      OCIS_URL: https://host.docker.internal:9200
      PROXY_ENABLE_BASIC_AUTH: true
      OCIS_INSECURE: true
      IDM_ADMIN_PASSWORD: admin
      WEB_UI_CONFIG_FILE: /etc/ocis/config.json
      # FRONTEND
      FRONTEND_SEARCH_MIN_LENGTH: 2
      FRONTEND_OCS_ENABLE_DENIALS: true
      FRONTEND_FULL_TEXT_SEARCH_ENABLED: true
    entrypoint: /bin/sh
    command: ['-c', 'ocis init || true; ocis server']
    volumes:
      - ./ocis/web.json:/etc/ocis/config.json
    restart: unless-stopped

  tika:
    image: apache/tika:2.8.0.0
    restart: unless-stopped
