version: '3.8'

services:
  ocis:
    environment:
      PROXY_AUTOPROVISION_ACCOUNTS: true
      PROXY_ROLE_ASSIGNMENT_DRIVER: oidc
      OCIS_OIDC_ISSUER: https://host.docker.internal:8443/realms/oCIS
      PROXY_OIDC_REWRITE_WELLKNOWN: true
      WEB_OIDC_CLIENT_ID: web
      PROXY_USER_OIDC_CLAIM: preferred_username
      PROXY_USER_CS3_CLAIM: username
      OCIS_ADMIN_USER_ID: ''
      OCIS_EXCLUDE_RUN_SERVICES: idp
      GRAPH_ASSIGN_DEFAULT_USER_ROLE: false

  postgres:
    image: postgres:alpine
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - keycloak_data:/var/lib/postgresql/data

  keycloak:
    build:
      context: ./keycloak
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - 8443:8443
      - 8080:8080
    environment:
      OCIS_DOMAIN: host.docker.internal:9200
      KC_HOSTNAME: host.docker.internal:8443
      KC_DB: postgres
      KC_DB_URL: 'jdbc:postgresql://postgres:5432/keycloak'
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_FEATURES: impersonation
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./keycloak/ocis-realm.json:/opt/keycloak/data/import/ocis-realm.json
    depends_on:
      - postgres

volumes:
  keycloak_data:
