version: '3.8'

services:
  ocis:
    environment:
      # users/gropups from ldap
      OCIS_LDAP_URI: ldaps://ldap:1636
      OCIS_LDAP_INSECURE: true
      OCIS_LDAP_BIND_DN: cn=admin,dc=owncloud,dc=com
      OCIS_LDAP_BIND_PASSWORD: admin
      OCIS_LDAP_GROUP_BASE_DN: ou=groups,dc=owncloud,dc=com
      OCIS_LDAP_GROUP_FILTER: (objectclass=owncloud)
      OCIS_LDAP_GROUP_OBJECTCLASS: groupOfNames
      OCIS_LDAP_USER_BASE_DN: ou=users,dc=owncloud,dc=com
      OCIS_LDAP_USER_FILTER: (objectclass=owncloud)
      OCIS_LDAP_USER_OBJECTCLASS: inetOrgPerson
      LDAP_LOGIN_ATTRIBUTES: uid
      OCIS_ADMIN_USER_ID: ddc2004c-0977-11eb-9d3f-a793888cd0f8
      IDP_LDAP_LOGIN_ATTRIBUTE: uid
      IDP_LDAP_UUID_ATTRIBUTE: ownclouduuid
      IDP_LDAP_UUID_ATTRIBUTE_TYPE: binary
      GRAPH_LDAP_SERVER_WRITE_ENABLED: true # assuming the external ldap is writable
      GRAPH_LDAP_REFINT_ENABLED: true # osixia has refint enabled
      OCIS_EXCLUDE_RUN_SERVICES: idm

  ldap:
    image: bitnami/openldap:2.6
    environment:
      LDAP_ROOT: dc=owncloud,dc=com
      LDAP_ADMIN_PASSWORD: admin
      LDAP_TLS_VERIFY_CLIENT: never
      LDAP_ENABLE_TLS: yes
      LDAP_TLS_CA_FILE: /opt/bitnami/openldap/share/openldap.crt
      LDAP_TLS_CERT_FILE: /opt/bitnami/openldap/share/openldap.crt
      LDAP_TLS_KEY_FILE: /opt/bitnami/openldap/share/openldap.key
    entrypoint:
      ['/bin/sh', '/opt/override.sh', '/opt/bitnami/scripts/openldap/run.sh']
    volumes:
      - ./ldap/ldif:/ldifs
      - ./ldap/schema:/schemas
      - ./ldap/override.sh:/opt/override.sh
