version: '3.8'

services:
  ocis:
    environment:
      STORAGE_SYSTEM_DRIVER: ocis # keep system data on ocis storage since this are only small files atm
      STORAGE_USERS_DRIVER: s3ng
      STORAGE_USERS_S3NG_ENDPOINT: http://minio:9000
      STORAGE_USERS_S3NG_REGION: default
      STORAGE_USERS_S3NG_ACCESS_KEY: minioadmin
      STORAGE_USERS_S3NG_SECRET_KEY: minioadmin
      STORAGE_USERS_S3NG_BUCKET: ocis-bucket

  minio:
    image: minio/minio:latest
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - 9000:9000
      - 9001:9001
    entrypoint: /bin/sh
    command:
      [
        '-c',
        "mkdir -p /data/ocis-bucket && minio server --console-address ':9001' /data",
      ]
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
